
package com.webservice.impl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "webserviceTestImpl", targetNamespace = "http://impl.webservice.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WebserviceTestImpl {


    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "sayAnything", targetNamespace = "http://impl.webservice.com/", className = "com.webservice.impl.SayAnything")
    @ResponseWrapper(localName = "sayAnythingResponse", targetNamespace = "http://impl.webservice.com/", className = "com.webservice.impl.SayAnythingResponse")
    @Action(input = "http://impl.webservice.com/webserviceTestImpl/sayAnythingRequest", output = "http://impl.webservice.com/webserviceTestImpl/sayAnythingResponse")
    public void sayAnything(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "contextInit", targetNamespace = "http://impl.webservice.com/", className = "com.webservice.impl.ContextInit")
    @ResponseWrapper(localName = "contextInitResponse", targetNamespace = "http://impl.webservice.com/", className = "com.webservice.impl.ContextInitResponse")
    @Action(input = "http://impl.webservice.com/webserviceTestImpl/contextInitRequest", output = "http://impl.webservice.com/webserviceTestImpl/contextInitResponse")
    public void contextInit();

}
