
package com.webservice.impl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "webserviceTestImplService", targetNamespace = "http://impl.webservice.com/", wsdlLocation = "http://127.0.0.1:8010/WS_Server/WebService?wsdl")
public class WebserviceTestImplService
    extends Service
{

    private final static URL WEBSERVICETESTIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException WEBSERVICETESTIMPLSERVICE_EXCEPTION;
    private final static QName WEBSERVICETESTIMPLSERVICE_QNAME = new QName("http://impl.webservice.com/", "webserviceTestImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:8010/WS_Server/WebService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WEBSERVICETESTIMPLSERVICE_WSDL_LOCATION = url;
        WEBSERVICETESTIMPLSERVICE_EXCEPTION = e;
    }

    public WebserviceTestImplService() {
        super(__getWsdlLocation(), WEBSERVICETESTIMPLSERVICE_QNAME);
    }

    public WebserviceTestImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WEBSERVICETESTIMPLSERVICE_QNAME, features);
    }

    public WebserviceTestImplService(URL wsdlLocation) {
        super(wsdlLocation, WEBSERVICETESTIMPLSERVICE_QNAME);
    }

    public WebserviceTestImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WEBSERVICETESTIMPLSERVICE_QNAME, features);
    }

    public WebserviceTestImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WebserviceTestImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WebserviceTestImpl
     */
    @WebEndpoint(name = "webserviceTestImplPort")
    public WebserviceTestImpl getWebserviceTestImplPort() {
        return super.getPort(new QName("http://impl.webservice.com/", "webserviceTestImplPort"), WebserviceTestImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WebserviceTestImpl
     */
    @WebEndpoint(name = "webserviceTestImplPort")
    public WebserviceTestImpl getWebserviceTestImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.webservice.com/", "webserviceTestImplPort"), WebserviceTestImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WEBSERVICETESTIMPLSERVICE_EXCEPTION!= null) {
            throw WEBSERVICETESTIMPLSERVICE_EXCEPTION;
        }
        return WEBSERVICETESTIMPLSERVICE_WSDL_LOCATION;
    }

}
